# Site settings
title: Lance's Blog
email: rlance.martin@gmail.com
description: "Riffing on science."
baseurl: ""
url: "http://lmart999.github.io"
twitter_username: RLanceMartin
github_username:  lmart999

# Build settings
markdown: redcarpet
permalink: pretty
